### ISSUE TITLE
No such file or directory: 'mining/bin/demo/base.sql' on running build_demo command

### ISSUE THREAD

**Issue by lerrua** [avelino/mining#247]
Guys,

After following a first installation step-by-step I'm getting this error on running `build_demo` command. 

```
$ python manage.py build_demo
OpenMining load demo system
Traceback (most recent call last):
  File "manage.py", line 118, in <module>
    cmds(default_map=default_map)
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 112, in build_demo
    build(level)
  File "/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/mining-0.2.0-py2.7-macosx-10.10-x86_64.egg/mining/bin/demo/build_admin.py", line 18, in build
    f = open('{}'.format(os.path.join(demo_path, 'base.sql')), 'r')
IOError: [Errno 2] No such file or directory: '/Users/leroy/.virtualenvs/mining/lib/python2.7/site-packages/mining-0.2.0-py2.7-macosx-10.10-x86_64.egg/mining/bin/demo/base.sql'
```

**Comment by lerrua** [comment]
I guess this error is in setup.py file, because the setup.py install works but doesn't install this base.sql file in my environment.

**Comment by luzfcb** [comment]
I suppose it's because the *.sql extension is not included in https://github.com/avelino/mining/blob/master/MANIFEST.in
